name: Unit test

on:
  pull_request:
    branches:
     - main
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm test
    - name: Upload report to artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: reports/
        