name: Unit test

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test
    - name: Store report
      run: echo "Report: $(find -name 'reports/index.html')"
      env:
        CI: true
    - name: Upload report to artifact
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: reports/index.html
    - name: Store reportJSON.txt file
      run: echo "Additional file: $(find -name 'reports/reportJSON.txt')"
      env:
        CI: true
    - name: Upload reportJSON.txt file to artifact
      uses: actions/upload-artifact@v2
      with:
        name: reportJSON_file
        path: reports/reportJSON.txt
